development:
  adapter: postgresql
  encoding: unicode
  database: cfenv
  pool: 5
  host: localhost
  username: cfenv
  password: password
  port: <%= ENV["BOXEN_POSTGRESQL_PORT"] || 5432 %>

test:
  adapter: postgresql
  encoding: unicode
  database: boxen_test
  username: cfenv
  password: password
  pool: 5
  port: <%= ENV["BOXEN_POSTGRESQL_PORT"] || 5432 %>

production:
  adapter: postgresql
  encoding: unicode
  database: cfenv
  pool: 5
  host: localhost
  username: cfenv
  password: password
  port: <%= ENV["BOXEN_POSTGRESQL_PORT"] || 5432 %>